spring:
  application:
    name: data-creation-service
  jpa: #database configuration
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/brm
    username: postgres
    password: root
    driverClassName: org.postgresql.Driver

#server settings
server:
  port: 8098
  contextPath: /dataCreation

# Logging
logging:
  level:
    org.springframework: INFO

